// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYgMiexbnpHen5P7_yRyT_U4MVIoOKEJo',
    appId: '1:1053208587558:web:bf8cc5859d47c6789665e7',
    messagingSenderId: '1053208587558',
    projectId: 'chatapp-646ee',
    authDomain: 'chatapp-646ee.firebaseapp.com',
    storageBucket: 'chatapp-646ee.firebasestorage.app',
    measurementId: 'G-4QR4HLW6C4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDAEnKXDQDwwb5BOTnk6vohrRZZs_ZtFY',
    appId: '1:1053208587558:android:4aa05e4e88318fc39665e7',
    messagingSenderId: '1053208587558',
    projectId: 'chatapp-646ee',
    storageBucket: 'chatapp-646ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ3_ncdeErT23zap_m16orW7D4OIOuGMM',
    appId: '1:1053208587558:ios:9210e2c9e23d2fd49665e7',
    messagingSenderId: '1053208587558',
    projectId: 'chatapp-646ee',
    storageBucket: 'chatapp-646ee.firebasestorage.app',
    iosBundleId: 'com.example.chatsapp',
  );
}
